name: "Build and push oecs-hub-web"
on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - "web/**"

  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
    paths:
      - "web/**"

  workflow_dispatch:

jobs:
  build-web:
    name: "Build and Push oecs-hub-web"
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      pull-requests: write
      checks: write
      packages: write
    with:
      service: oecs-hub-web
      push: ${{ github.event_name != 'pull_request' }}
      repository: oecs-hub-web
      dockerfile: "./web/Dockerfile"
      context: "./web"
    secrets: inherit
